name: Go (Lint)
on: [push, pull_request]
jobs:

  golangci-lint:
    name: runner / golangci-lint (pre-build docker image)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

          args: --new-from-rev=e0a5614e47d349897~0
